### ISSUE TITLE
what's the point?

### ISSUE THREAD

**Issue by eridal** [xeoncross/1kb-PHP-MVC-Framework#3]
I understand you are trying to fit your code into 1kb .. but it's impossible to read or follow -- besides php's libraries does not have restrictions such as css or js libraries; where the file size really matters.

--- Update:

ok, nevermind, I just saw the "last updated 3 years ago" :)

**Comment by xeoncross** [comment]
Code Golf has many points including:
- Prove language grasp
- Slim existing solutions to prove feature-vs-core requirements
- Answer Dares
- For fun

:)
