### ISSUE TITLE
getenv('REQUEST_URI')  return empty  when  using  php built-in server 

### ISSUE THREAD

**Issue by tablecell** [xeoncross/1kb-PHP-MVC-Framework#6]
test.php
```T
<?php
echo 'REQUEST_URI';


echo getenv('REQUEST_URI');
```
php -S localhost:88

curl htttp://localhost:88/aa/bbb

**Comment by xeoncross** [comment]
`REQUEST_URI` is a parameter you must define as a parameter provided by your server (in this case PHP)
